- hosts: ceph1
  any_errors_fatal: true
  become: true
  tasks:

#    - name: Copy private repo file
#      copy:
#        src: files/ceph3.repo
#        dest: /etc/yum.repos.d/ceph3.repo
#        owner: root
#        group: root
#        mode: 0644

    - name: Copy private repo file
      template:
        src: "templates/ceph3.repo.j2"
        dest: "/etc/yum.repos.d/ceph3.repo"
        backup: yes

    - name: Run yum repolist
      command: yum repolist
    
    - name: Install docker
      yum:
        name: docker
        state: latest

    - name: Make sure docker is stopped
      systemd:
        name: docker
        state: stopped

    - import_tasks: create_lvol_fs.yml

    - name: Copy docker-storage-setup file
      copy:
        src: files/docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: Configure Docker storage setup
      command: /usr/bin/docker-storage-setup

    - name: Copy mount systemd unit for docker lv
      copy:
        src: files/var-lib-docker.mount
        dest: /etc/systemd/system/var-lib-docker.mount
        owner: root
        group: root 
        mode: 0644
   
    - name: Mount docker lv
      systemd:
        name: var-lib-docker.mount
        enabled: yes
        state: started
        masked: no

    - name: Copy registries.conf
      copy:
        src: files/registries.conf
        dest: /etc/containers/registries.conf
        owner: root
        group: root 

    - name: Start docker
      systemd:
        name: docker
        enabled: yes
        state: started
        masked: no

    - name: Copy s3cmd rpm
      copy:
        src: "files/{{ s3cmd_rpm }}"
        dest: "/root/{{ s3cmd_rpm }}"
        owner: root
        group: root 

    - name: Install s3cmd
      yum:
        name: "/root/{{ s3cmd_rpm }}"
        state: present
