- hosts: bastion
  any_errors_fatal: true
  become: true
  tasks:

#  - name: Install pkgs
#    yum:
#      name: "{{ item }}"
#      state: latest
#    with_items:
#      - git
#      - ansible
#      - docker
#      - lvm2
#      - httpd
#      - yum-utils
#      - createrepo

#
#Create fs for repos
#
  - name: partition disks
    parted:
      device: "{{ item }}"
      number: 1
      state: present
      align: optimal
    with_items:
      -  "{{ lv_values.disk }}"
  
  - name: create vgs
    lvg:
      force: yes
      pvs: "{{ item.disk }}"
      pesize: 4
      state: present
      vg: "{{ item.name }}"
    with_items:
      -  { disk: "{{ lv_values.disk }}1", name: "{{ lv_values.vg_data }}" }
  
  - name: Create logical volumes
    lvol:
      vg: "{{ item.vg }}"
      lv: "{{ item.name }}"
      size: "{{ item.size }}"
      state: present
    with_items:
      - { vg: "{{ lv_values.vg_data }}", name: "{{ lv_values.lv_name }}" , size: "{{ lv_values.data_size }}" }
  
  - name: Format devices
    filesystem:
      fstype: "{{ lv_values.filesystem }}"
      dev: /dev/{{ item.vg }}/{{ item.name }}
    with_items:
      - { vg: "{{ lv_values.vg_data }}", name: "{{ lv_values.lv_name }}"}
  
  - name: Create mount folders
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ lv_values.repo_path }}"

  - name: Mount logical volumes
    mount:
      name: "{{ item.dest }}"
      src: /dev/mapper/{{ item.vg }}-{{ item.name }}
      fstype: "{{ lv_values.filesystem }}"
      opts: "{{ item.opts }}"
      state: mounted
    with_items:
      - { vg: "{{ lv_values.vg_data }}", dest: "{{ lv_values.repo_path }}" , name: "{{ lv_values.lv_name }}" , opts: "defaults" }
   
  - name: Ensure devices are mounted
    args:
     warn: no
    command: mount -a
    register: check_mounts
    changed_when: check_mounts.rc != 0
   
  - name: Restore label
    command: restorecon -Rv "{{ item }}"
    with_items:
      - "{{ lv_values.repo_path }}"

#
# start and configure httpd to enable repo
#

  - name: Start httpd
    systemd:
      name: httpd
      enabled: yes
      state: started
      masked: no


#
#Install and configure ceph-ansible for each DC
#

  - name: Install ceph-ansible and ansible on bastion
    yum:
      name: ceph-ansible
      state: latest

  - name: Create install dirs
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/dc1
      - /root/dc2

  - name: synchronize ceph-ansible dirs for each dc
    synchronize:
      src: /usr/share/ceph-ansible
      dest: "{{ item }}"
    with_items:
      - /root/dc1/
      - /root/dc2/
    delegate_to: "{{ inventory_hostname }}"

  - name: Copy ansible.cfg
    copy:
      src: "../ansible.cfg"
      dest: "{{ item }}"
      owner: root
      group: root
    with_items:
     - "/etc/ansible/ansible.cfg"
     - "/root/dc1/ceph-ansible/ansible.cfg"
     - "/root/dc2/ceph-ansible/ansible.cfg"

  - name: Copy ansible.cfg
    copy:
      src: "../ansible.cfg"
      dest: "{{ item }}"
      owner: root
      group: root
    with_items:
     - "/etc/ansible/ansible.cfg"
     - "/root/dc1/ceph-ansible/ansible.cfg"
     - "/root/dc2/ceph-ansible/ansible.cfg"

  - name: Copy inventory
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
    with_items:
      - { src: '../inventory_dc1', dest: '/root/dc1/ceph-ansible/inventory' }
      - { src: '../inventory_dc2', dest: '/root/dc2/ceph-ansible/inventory' }


#
# Dowload/sync repos on bastion host
#

  - name: Copy create_repos script
    copy:
      src: "../hacks/sync-repos.sh"
      dest: "{{ item }}"
      owner: root
      group: root
    with_items:
      - /root/

