- hosts: metricsall
  any_errors_fatal: true
  become: true
  tasks:

    - import_tasks: task_config_repos.yaml
    - import_tasks: task_create_lvol_fs.yaml
    - import_tasks: task_configure_docker.yaml


    - name: "Install cephmetrics"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - ceph-common
        - cephmetrics-ansible
    
    - name: "Added folder for ceph-metrics files"
      file: 
        name: "/usr/share/cephmetrics-ansible/group_vars"
        state: directory
        mode: 0755
    
    - name: "Add templates for ceph metrics"
      template:
        src: "templates/{{ item }}.j2"
        dest: "/usr/share/cephmetrics-ansible/group_vars/{{ item }}"
      with_items:
        - all_metrics.yaml
    
    - name: "Add templates for ceph metrics"
      copy:
        src: "../ansible.cfg"
        dest: "/usr/share/cephmetrics-ansible/"
