- hosts: metricsall
  any_errors_fatal: true
  become: true
  tasks:

    - import_tasks: task_config_repos.yaml
    - import_tasks: task_config_hosts.yaml
    - import_tasks: task_create_lvol_fs.yaml
    - import_tasks: task_configure_docker.yaml
    - import_tasks: task_config_ntp.yaml
    - import_tasks: task_config_ssh.yaml


    - name: "Install cephmetrics"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - ceph-common
        - cephmetrics-ansible
    
    - name: "Added folder for ceph-metrics files"
      file: 
        name: "/usr/share/cephmetrics-ansible/group_vars"
        state: directory
        mode: 0755
    
    - name: "Add templates for ceph metrics"
      template:
        src: "templates/{{ item }}.j2"
        dest: "/usr/share/cephmetrics-ansible/group_vars/all.yml"
      with_items:
        - all_metrics_dc1.yaml
      when: inventory_hostname == "metricsd"

    - name: "Add templates for ceph metrics"
      template:
        src: "templates/{{ item }}.j2"
        dest: "/usr/share/cephmetrics-ansible/group_vars/all.yml"
      with_items:
        - all_metrics_dc2.yaml
      when: inventory_hostname == "metrics4"
    
    - name: "Add templates for ceph metrics"
      copy:
        src: "../ansible.cfg"
        dest: "/usr/share/cephmetrics-ansible/"

    - name: Copy inventory
      copy:
        src: "files/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
      with_items:
        - { src: "inventory_dc1" , dest: '/usr/share/cephmetrics-ansible/inventory' }
      when: inventory_hostname == "metricsd"

    - name: Copy inventory
      copy:
        src: "files/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
      with_items:
        - { src: "inventory_dc2" , dest: '/usr/share/cephmetrics-ansible/inventory' }
      when: inventory_hostname == "metrics4"

    - name: Copy keys for ansible
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0400
      with_items:
        - { src: "files/key"  , dest: '/root/.ssh/id_rsa' }
        - { src: "files/key.pub" , dest: '/root/.ssh/id_rsa.pub' }

  handlers:
    - import_tasks: handlers_common.yaml

