- hosts: ceph
  any_errors_fatal: true
  become: true
  tasks:

    - name: Copy private repo file
      template:
        src: "templates/ceph3.repo.j2"
        dest: "/etc/yum.repos.d/ceph3.repo"
        backup: yes

    - name: Run yum repolist
      command: yum repolist

    - import_tasks: task_create_lvol_fs.yaml
    - import_tasks: task_config_network.yaml
    - import_tasks: task_config_hosts.yaml
    - import_tasks: task_configure_docker.yaml
    - import_tasks: task_install_s3cmd.yaml
    - import_tasks: task_config_ssh.yaml

  handlers:
    - import_tasks: handlers_common.yaml
  

