---
    - name: Copy private repo file
      template:
        src: "templates/ceph3.repo.j2"
        dest: "/etc/yum.repos.d/ceph3.repo"
        backup: yes

    - name: Run yum repolist
      command: yum repolist
