---
    - name: Run yum repolist
      command: yum repolist

    - name: Install docker
      yum:
        name: "{{ item }}"
        state: latest
      with_items: 
        - docker
        - ceph-common

    - name: Make sure docker is stopped
      systemd:
        name: docker
        state: stopped

    - name: Copy docker-storage-setup file
      copy:
        src: files/docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: Configure Docker storage setup
      command: /usr/bin/docker-storage-setup

    - name: Copy mount systemd unit for docker lv
      copy:
        src: files/var-lib-docker.mount
        dest: /etc/systemd/system/var-lib-docker.mount
        owner: root
        group: root
        mode: 0644
  
    - name: Mount docker lv
      systemd:
        name: var-lib-docker.mount
        enabled: yes
        state: started
        masked: no

    - name: Copy registries.conf
      copy:
        src: files/registries.conf
        dest: /etc/containers/registries.conf
        owner: root
        group: root

    - name: Start docker
      systemd:
        name: docker
        enabled: yes
        state: started
        masked: no
